language: ruby
rvm:
- 2.1
install: gem install rake --version='10.4.2'
install: gem install rake jekyll html-proofer
script: jekyll build && htmlproof ./_site --file-ignore /presentations/ --href-ignore ["#"]
# script: "rake test"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true