# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     ["fenced code blocks", "autolink", "tables", "with_toc_data"]
pygments:         true
kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Dan Swick
tagline:          danswick.com
url:              danswick.com
paginate:         2
author:
  name:           Dan Swick
  url:            https://twitter.com/danswick
  email:          dan.swick@gmail.com
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
  Projects: '/projects'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/danswick/danswick.github.io
name: danswick.com
description: a personal weblog odyssey
url: http://danswick.com

# Plugins
gems:             ['jekyll-sitemap']