# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     ["fenced code blocks", "autolink", "tables", "with_toc_data"]
highlighter:      rouge
kramdown:
  input:          GFM

# Permalinks
permalink:        /posts/:title

# Setup
title:            Dan Swick
tagline:          danswick.com
url:              danswick.com
baseurl:          /
paginate:         2
author:
  name:           Dan Swick
  url:            https://twitter.com/danswick
  email:          dan.swick@gmail.com
pages_list:
  About: 'about/index.html'
  Words: 'words/index.html'
  Projects: 'work/index.html'
  Feed: 'atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/danswick/danswick.github.io
name: danswick.com
description: a personal weblog odyssey
url: http://danswick.com

# Plugins
gems:             ['jekyll-sitemap']
