# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dan Swick
tagline:          danswick.com
url:              danswick.com
paginate:         1
author:
  name:           Dan Swick
  url:            https://twitter.com/danswick
  email:          dan.swick@gmail.com
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/danswick/danswick.github.io
